### ISSUE TITLE
Support React 15.5

### ISSUE THREAD

**Issue by ethanselzer** [ethanselzer/react-image-magnify#10]
Support for React 15.5 is on the react-image-magnify roadmap!

Tasks
- [x] Upgrade react-cursor-position dependency
- [x] Upgrade react-hover-observer dependency
- [x] Upgrade react-image-magnify

**Comment by ethanselzer** [comment]
Closing with [v1.8 release](https://github.com/ethanselzer/react-image-magnify/releases/tag/v1.8.0). Version 1.8 package has been [published to NPM](https://www.npmjs.com/package/react-image-magnify).

@damien916 - Thanks for helping to raise the priority of upgrading to React 15.5 by opening https://github.com/ethanselzer/react-cursor-position/issues/5. And thanks for your continued support of the project!

**Comment by damien916** [comment]
Thank you @ethanselzer !
