### ISSUE TITLE
Zoom container not visible with slick

### ISSUE THREAD

**Issue by jitenderchand1** [ethanselzer/react-image-magnify#11]
Zoom image container not  visible when using it with slick slider. Reason is overflow:hidden being set on slick items.

Should have been option to render zoom container inside any container. 

<ReactImageMagnify { ...{
                  smallImage:{
                    alt,
                    isFluidWidth: true,
                    src: abc.jpg
                  },
                  largeImage: {
                    alt,
                    src: abc_large.jpg,
                    width: 1200,
                    height: 1800
                  },
                  **renderTo:'#containerId',**
                }} />

**Comment by ethanselzer** [comment]
Hi @jitenderchand1, Thanks for opening this issue. You raise an interesting point. I will investigate and post back here with my findings.

**Comment by ethanselzer** [comment]
Hi @jitenderchand1, 

I am considering addressing the issue you identified by extending the API of react-cursor-position to support a user specified large image view that could be outside the markup tree of a carousel or other containing elements. 

In the meantime there may be a workaround for the issue using position: fixed. Please see this [editable CodePen](https://codepen.io/ethanselzer/pen/oeaVLL) demonstrating the approach. Note the use of the prop named `enlargedImageContainerStyle`. Another workaround might be to specify `over` as the value to the prop named `enlargedImagePosition`.  Please let me know your thoughts on these ideas or if any of this need further clarification.

Thanks again for raising this issue. I appreciate it!

**Comment by ethanselzer** [comment]
Hi @jitenderchand1 - I'm closing this for now, due to inactivity. But, please feel free to reopen it if you have questions or feedback.

**Comment by jitenderchand1** [comment]
Hi @ethanselzer I have tried your solution but it seems not working with the slick slider.

slick slider use **translate** property from CSS and position **fixed** have an issue with translate.

fixed CSS property behave like absolute when we use it with translate. it's a known bug in chrome

**Comment by ethanselzer** [comment]
Hi @jitenderchand1 - Thanks for the feedback. I'm sorry the solution I suggested is not working. Are you using [react-slick](https://www.npmjs.com/package/react-slick)?

**Comment by eddy20vt** [comment]
Hi! do you get any solution for that? I have the same problem... I can't use ReactImageMagnify with react-slick.
Thanks in advance.

**Comment by ethanselzer** [comment]
@eddy20vt - Thanks for your comment. Here is an example of [integrating react-image-magnify with react-slick](https://ethanselzer.github.io/react-image-magnify/#/react-slick) and here is the [source code](https://github.com/ethanselzer/react-image-magnify/blob/master/example/src/pages/ReactSlick.js). The example supports displaying the enlarged image over the small image, but does not yet support displaying the enlarged image to the side of the small image. Support for displaying the enlarged image to the side with react-slick is being developed, but is not ready yet. Let me know if the example works for your use case.

**Comment by eddy20vt** [comment]
@ethanselzer At the begin I needed the image to the side, but I changed my design and I'm using the enlarged image over the small one.
Good job! and thanks for your feedback. 
It's working very well and looks nice in mobile view.

**Comment by ethanselzer** [comment]
@eddy20vt - I'm glad it is working for you! Thanks for letting me know. If you find react-image-magnify useful, please consider starring it on GitHub. Starring helps to grow the project, which benefits everyone.

**Comment by ethanselzer** [comment]
This issue is addressed in [v2.6.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.6.0). Also see related issue #19.

**Comment by IndigoHollow** [comment]
Hello, could you please renew your source code link from the 12 Feb 2018 comment, it is now 404. Thank you very much!
