### ISSUE TITLE
Unexpected character '`' 

### ISSUE THREAD

**Issue by vidries** [ethanselzer/react-image-magnify#15]
it will not pass in jenkins, i am pretty sure about that, the error messages just like this :    
Unexpected character '`'

**Comment by ionutzp** [comment]
It's because of this required package:
https://github.com/thejameskyle/react-required-if/blob/master/index.js#L5

The change there was made 4 days ago, also there is no dist for that package

**Comment by ethanselzer** [comment]
@vidries, @ionutzp - Thank you very much for identifying and researching this issue. I really appreciate it! A [new version of react-image-magnify](https://www.npmjs.com/package/react-image-magnify) @2.1.1 has been released. It clamps the version of react-require-if at 1.0.1, which is known to be okay. Please verify react-image-magnify@2.1.1 resolves your issues. If all is well, I will update the [release notes](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.1.1) to include a message that the latest release resolves this issue. Thanks again!

**Comment by vidries** [comment]
@ionutzp  @ethanselzer  all is well. nice work !

**Comment by ethanselzer** [comment]
Resolved by [v2.1.1 release](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.1.1)
