### ISSUE TITLE
Can we use container id where to show zoom content? 

### ISSUE THREAD

**Issue by sushilnykaa** [ethanselzer/react-image-magnify#19]
Can we use separate container where we can show the zoomable image when hover on actual image?

**Comment by ethanselzer** [comment]
Hi @sushilnykaa, Thanks for opening this issue. Unfortunately, react-image-magnify does not support rendering the enlarged image in an element of your choosing. Sorry about that. It is possible to [render the enlarged image in-place](https://ethanselzer.github.io/react-image-magnify/#/in-place) by setting the prop named `enlargedImagePosition` to `over`. Please let me know if that works for your use case. Also, can you tell me why you would like to specify an element to render the enlarged image?

**Comment by sushilnykaa** [comment]
Hey Ethan,
Thanks to revert me back, as we are facing issue to integrate slick with react-image-magnifier , as the slick added overflow hidden so the enlarge image won't show properly or hide in slick container because of overflow, 

Can we have any solution for this kind of problem ?

**Comment by ethanselzer** [comment]
Hi @sushilnykaa, 
Thanks for the information, it is helpful. To integrate react-image-magnify with react-slick, I think the only solution, at this time, is to implement [in-place enlargement](https://ethanselzer.github.io/react-image-magnify/#/in-place). Is in-place enlargement an option for your use case?

**Comment by sushilnykaa** [comment]
Hi Ethan , actually this won't because as per the mockups provided the container is different for enlarge image,

**Comment by jitenderchand1** [comment]
I am facing the similar issue with my react App. No solution so far :(

**Comment by gayanhewa** [comment]
@ethanselzer is it possible to specify the which side the large image should appear. ie left or right side?

**Comment by ethanselzer** [comment]
@gayanhewa - Support for specifying the large image display to the left is planned, but unfortunately has not been implemented yet. There is a [work around](https://codepen.io/ethanselzer/pen/xPQoZa?editors=0110) that may help. Note the `enlargedImageContainerClassName` prop on ReactImageMagnify and see the corresponding CSS on 33. Please let me know if you have any questions. Thanks!

**Comment by gayanhewa** [comment]
Thanks for getting back @ethanselzer , I was able to use one of the pops to pass and override styles.

**Comment by ethanselzer** [comment]
@gayanhewa - I'm glad you found a solution! Support for positioning the large image to the left of the initial image via props is planned for the next major version release.

**Comment by ethanselzer** [comment]
@sushilnykaa, @jitenderchand1 - Support for rendering the enlarged image to a container of your choosing landed in [v2.6.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.6.0). Please have a look. Thanks again for creating this issue. I really appreciate it.

**Comment by ethanselzer** [comment]
Closing as fixed by [v2.6.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.6.0)
