### ISSUE TITLE
How to implement events over image container i.e. onClick 

### ISSUE THREAD

**Issue by psingh157** [ethanselzer/react-image-magnify#23]
Hi, as I was working on a project where I want functionality like when I click on image it'll open a modal and show zoom on hover functionality there (same like on image container hover). So how I call onClick event on that image. Please help!
Thanks

**Comment by ethanselzer** [comment]
Hi @psingh157 - Thanks for opening this issue. I think you can listen for click events on the parent component, that contains react-image-magnify. Here is an [example on CodePen](https://codepen.io/ethanselzer/pen/mXWKrb?editors=0110). Let me know if it needs more explanation or if I have misunderstood your question.

**Comment by psingh157** [comment]
Hi, thank you for the response, as in my project Prettier isn't allowing onClick on div. But, OK, I'll see.
Another thing some styles are not applying on image as I am using imageStyle object, but it isn't working.
And if I give className to image, container, etc. then where I have to write those class declaration and properties.

**Comment by ethanselzer** [comment]
@psingh157 - You're welcome! If you find react-image-magnify useful, please consider starring it on GitHub. Starring helps to grow the project, which benefits all who use it. Thanks!

**Comment by little-white** [comment]
it helps me a lot,thx
