### ISSUE TITLE
how do srcset and sizes parameters work?

### ISSUE THREAD

**Issue by eddy20vt** [ethanselzer/react-image-magnify#24]
I've trying to change these parameters but nothing is happening.

The only change that I can see is when I put an image in the srcset, this override the src parameter but if I add more than one image separate by comma, nothings changes.

Could you give some example or explain a bit how these parameters work?

Thanks in advance.

**Comment by ethanselzer** [comment]
@eddy20vt - `srcset` and `sizes` are attributes of the HTML image element. Please see the resources listed below for more information. Here is [an example](https://ethanselzer.github.io/react-image-magnify/#/) that utilizes `srcset` and `sizes`. If you inspect the network tab you should see a smaller image requested when the browser window is narrow compared to when the browser window is wide.

https://bitsofco.de/the-srcset-and-sizes-attributes/
https://cloudfour.com/thinks/responsive-images-101-definitions/

**Comment by ethanselzer** [comment]
@eddy20vt I'm closing this issue but if you have further questions please reopen it, or create another one.

**Comment by buzzguy** [comment]
This is happening to me as well. I'm providing a string of srcset images to `smallImage` and `largeImage` but does not render:
props:
![image](https://user-images.githubusercontent.com/1154836/193707804-6a4ad2f7-8843-4fe9-a33d-125193597b6e.png)

render image element:
![image](https://user-images.githubusercontent.com/1154836/193707844-cbfbc25d-8582-4ffe-ac74-d9f2fa877302.png)
