### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by eddy20vt** [ethanselzer/react-image-magnify#25]
Please, update package.json to get the last version of "react-cursor-position".
From
"react-cursor-position": "2.4.0"
to 
"react-cursor-position": "2.4.1"

I need the last fix about constants.

Thanks.

**Comment by ethanselzer** [comment]
Hey @eddy20vt - Thanks for opening this issue! Please see [release 2.5.2](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.5.2). The NPM package has been updated also. Please have a look. Sorry for the trouble!

**Comment by eddy20vt** [comment]
Thank you for your fast response!

**Comment by ethanselzer** [comment]
Fixed by [release 2.5.2](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.5.2).
