### ISSUE TITLE
Feature request: toggle for inverted lens

### ISSUE THREAD

**Issue by nilsklimm** [ethanselzer/react-image-magnify#31]
For our project, we need a slightly different lens layout, which is not possible to realize with the current version of the module.

**Current layout:** 4 rectangles (DIV's) with transparent black background color are aranged around the magnified area to darken the rest of the small image.

**What we need:** 1 rectangle (DIV) with transparent white background and a box shadow, which fits / overlaps the magnified area of the small image.

**Recommendation:** We implement both layouts and make them toggleable.

I could develop this and send you a pull request...

Cheers

**Comment by ethanselzer** [comment]
Hi @nilsklimm - Thanks for opening this issue. The feature you have requested is in development and will be published in the next release. It has also been discussed on #21.

**Comment by ethanselzer** [comment]
@nilsklimm - A new lens option has been [released in v2.7.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.7.0). Please have a look and let me know your thoughts. There is [a demo example](https://ethanselzer.github.io/react-image-magnify/#/lens) that includes an optional restyling idea. Thanks for supporting the initiative!

**Comment by ethanselzer** [comment]
Closing as fixed in [v2.7.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.7.0).

**Comment by nilsklimm** [comment]
Works great! Thank you!
