### ISSUE TITLE
Preserve swipe gesture when used with react-slick

### ISSUE THREAD

**Issue by Coriou** [ethanselzer/react-image-magnify#50]
Awesome component I'd like to integrate with Slick (react-slick). Everything works as or better than expected, except for the touch swipe gesture that is not passed to Slick. 

Meaning, when I'm rendering this component as Slick slides, I can't swipe using touch gestures (works with the mouse).

Is there a possible fix for this ? Where should I look for it ? I can't use this component is breaking touch support for Slick which is a must-have for me, but I really want to use it because it's otherwise brilliant.

**Comment by ethanselzer** [comment]
@Coriou - Sorry you're having trouble. Swipe gestures seem to work for me on the [react-slick integration example](https://ethanselzer.github.io/react-image-magnify/#/react-slick). Maybe I'm missing something. The react-slick integration example code is [here](https://github.com/ethanselzer/react-image-magnify/blob/master/example/src/components/ReactSlick.js#L60-L92). Let me know what you find.

**Comment by Coriou** [comment]
@ethanselzer - Hey, you're right, it works. I have just spent 3 or 4 hours trying to debug this issue I'm having, without any form of success whatsoever.

I even [re-created a Pen](https://codepen.io/coriou/pen/PdMKPb), in which the touch swipe gesture works as expected, yet it doesn't work in my project with the exact same code. 

I tried removing all of my own style, I tried upgrading / downgrading the versions of the underlying Slick Carousel (both style and JS). I tried moving my component to different parts of my app, I tried having it render as a "top" element (not in any other container)...

Honestly, I feel totally hopeless, I just wasted hours and hours and I still don't have a single clue as to what is wrong.

Don't think it's an issue with this component though, as when I try to reproduce outside of my project it works fine.

If anyone has ANY idea, please feel free to let me know because right now I just don't know what to do...

**Comment by Coriou** [comment]
Hey, I actually was able to reproduce it ! I don't know what changes, again this issue is a complete mystery for me.

I created a [test repo](https://github.com/Coriou/ReactMagnifySlickSwipe) with my buggy code. If you run it you will see everything working as expected, except that it will not allow for that swipe carousel gesture from a touch device (will work with the mouse).

Here's a [little video](https://transfer.sh/r6Gw9/ReactMagnifySlickSwipe.mov) of what it does. You will see that when I move my mouse from left to right, or left to right, I'm actually holding down a click trying to swipe from one slide to another but nothing happens. All the other controls are functional and the magnification is also working in place.

Tested with : 

- simulated touch events in Firefox & Chrome
- iOS simulators (iOS 12 only, but tried different devices)
- real iOS devices

**Comment by Coriou** [comment]
Do you know which is the latest "working" version @kskonecka ? If not, which version were you using last ? I'd like a downgrade a try when I get a chance.

**Comment by ethanselzer** [comment]
@Coriou, @kskonecka - Thanks for your great feedback. It has been very helpful. I think the issue may be corrected in v2.7.3. Please have a look.

**Comment by Coriou** [comment]
Hey @ethanselzer, thank you so much for looking into this issue.

As a test, I've bumped the version of my [test repo](https://coriou.github.io/ReactMagnifySlickSwipe/) and swipe is working as expected !

I'll make sure to let you know if I have any issues in my real project, however I don't expect any.

Thanks for the great component and support on this issue !

Can close for now

**Comment by ethanselzer** [comment]
Fixed by [v2.7.3](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.7.3)
