### ISSUE TITLE
Custom sizes to lens and enlargedImageContainer

### ISSUE THREAD

**Issue by andreatosatto90** [ethanselzer/react-image-magnify#9]
Is it possibile to set a custom size to the area where the zoomed image is rendered?
I tried with no luck some combination of styles via props.  I'm also looking for a solution to the same issue but related to lens size.

Thanks and great work with this component!

**Comment by ethanselzer** [comment]
Hi @andreatosatto90,

Thanks for opening this issue! Unfortunately react-image-magnify does not yet support different size containers for small and enlarged images. However, I am interested in adding this feature in the near future. I'm wondering if you could tell me a little about your use case to help me better understand your vision.

Kind regards,
Ethan

**Comment by andreatosatto90** [comment]
Hi @ethanselzer,

In my use case I need to zoom an image detail with the full image still visible, the right horizontal space is limited, almost half of the image width. I think is very common in e-commerce website,

**Comment by ethanselzer** [comment]
Hi @andreatosatto90,

Thanks for the information. Although it seems natural for a developer to control the dimensions of the enlarged image container with CSS, I think that may introduce complexity in this module. Do you think an API that offered an option to specify the dimensions of the enlarged image container as a set of two numbers, width and height, would be strange?

Ethan

**Comment by andreatosatto90** [comment]
I agree with you, I played a little with your code and the CSS solution is too complex. Your solution seems to me the best

**Comment by ethanselzer** [comment]
Okay cool! This feature is on the react-image-magnify roadmap. In the next release, I'm committed to support mouse and touch environments with a single component, but I think this feature could be the following priority. I'll post progress updates on this issue.

**Comment by Borispp** [comment]
Any updates with this issue? (

**Comment by ethanselzer** [comment]
Hi @Borispp - Thanks for your comment. To help me create requirements for this feature, I'm wondering if you would share your reason for wanting it.

**Comment by ethanselzer** [comment]
@andreatosatto90, @Borispp - Thanks again for opening and commenting on this issue! I think it is resolved in [v2.5.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.5.0). Please have a look and let me know if you have any questions or comments. @Borispp, if you find this project useful, please consider staring it on GitHub. Starring helps to grow the project, which benefits everyone using it. @andreatosatto90, Thank you for starring the project way back in May of last year!

**Comment by ethanselzer** [comment]
Hey guys, thanks for starting and contributing to this issue. I really appreciate it. I'm closing this as fixed by [v2.5.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.5.0), but let me know if there is something I missed.
